# Generated by Django 5.2.9 on 2026-05-21 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('passport_file', models.FileField(blank=True, help_text='Файл скана паспорта', null=True, upload_to='passports/', verbose_name='Скан паспорта')),
                ('name_change_file', models.FileField(blank=True, help_text='Файл скана документа о смене ФИО', null=True, upload_to='name_changes/', verbose_name='Скан документа о смене ФИО')),
                ('education_file', models.FileField(blank=True, help_text='Файл скана документа об образовании', null=True, upload_to='education/', verbose_name='Скан документа об образовании')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
            ],
            options={
                'verbose_name': 'Обучаемый',
                'verbose_name_plural': 'Обучаемые',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_enrollment_application', models.BooleanField(default=False, verbose_name='Заявление на зачисление')),
                ('has_personal_data_consent', models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата и время подгрузки')),
                ('operator', models.CharField(blank=True, help_text='ФИО или ID оператора, проверившего документы', max_length=150, null=True, verbose_name='Оператор проверки')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время проверки')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='parser.student', verbose_name='Обучаемый')),
            ],
            options={
                'verbose_name': 'Маршрут учета',
                'verbose_name_plural': 'Маршруты учета',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
