# Generated by Django 5.2.9 on 2026-05-21 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, default='', help_text='Уникальный ID студента из системы FIRPO', max_length=50, verbose_name='ID Студента'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_file',
            field=models.FileField(blank=True, null=True, upload_to='education/', verbose_name='Скан документа об образовании'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_change_file',
            field=models.FileField(blank=True, null=True, upload_to='name_changes/', verbose_name='Скан документа о смене ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='passports/', verbose_name='Скан паспорта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Статус проверки')),
                ('date_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оператор')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='parser.student', verbose_name='Обучаемый')),
            ],
            options={
                'verbose_name': 'Поступление на курс',
                'verbose_name_plural': 'Поступления на курс',
                'ordering': ['-student__created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Статус проверки')),
                ('date_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оператор')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='parser.student', verbose_name='Обучаемый')),
            ],
            options={
                'verbose_name': 'Договор на обучение',
                'verbose_name_plural': 'Договоры на обучение',
                'ordering': ['-student__created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Статус проверки')),
                ('date_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оператор')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='parser.student', verbose_name='Обучаемый')),
            ],
            options={
                'verbose_name': 'Заявление на зачисление',
                'verbose_name_plural': 'Заявления на зачисление',
                'ordering': ['-student__created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalDataConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Статус проверки')),
                ('date_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оператор')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='parser.student', verbose_name='Обучаемый')),
            ],
            options={
                'verbose_name': 'Согласие на обработку ПДн',
                'verbose_name_plural': 'Согласия на обработку ПДн',
                'ordering': ['-student__created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Статус проверки')),
                ('date_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата')),
                ('operator', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оператор')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='parser.student', verbose_name='Обучаемый')),
            ],
            options={
                'verbose_name': 'Первичные документы',
                'verbose_name_plural': 'Первичные документы',
                'ordering': ['-student__created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EnrollmentRoute',
        ),
    ]
