# Generated by Django 5.2.9 on 2026-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_student_course_student_email_student_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Текущий статус'),
        ),
    ]
