# Generated by Django 5.2.9 on 2026-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id_irpo',
            field=models.CharField(blank=True, null=True, verbose_name='ID студента'),
        ),
    ]
