# Generated by Django 5.2.9 on 2026-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_student_student_id_irpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='student_id_irpo',
            field=models.CharField(blank=True, null=True, verbose_name='ID студента'),
        ),
        migrations.AddField(
            model_name='educationcontract',
            name='student_id_irpo',
            field=models.CharField(blank=True, null=True, verbose_name='ID студента'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='student_id_irpo',
            field=models.CharField(blank=True, null=True, verbose_name='ID студента'),
        ),
        migrations.AddField(
            model_name='personaldataconsent',
            name='student_id_irpo',
            field=models.CharField(blank=True, null=True, verbose_name='ID студента'),
        ),
        migrations.AddField(
            model_name='primarydocuments',
            name='student_id_irpo',
            field=models.CharField(blank=True, null=True, verbose_name='ID студента'),
        ),
    ]
